### ISSUE TITLE
Could not find a version that satisfies the requirement gpt-code-assistant

### ISSUE THREAD

**Issue by sneko** [narenmanoharan/gpt-code-assistant#5]
Hi,

Just wanted to try out "gpt-code-assistant" but it seems not published on the pip registry whereas it's mentioned in the setup step https://github.com/narenmanoharan/gpt-code-assistant#installation . Did I miss something?

Note that on the other side, I do see https://pypi.org/project/gpt-code-search/ (by the way I tried this older version but not working at all... always getting the error "Dictionary values must be serializeable to JSON" even on your own codebase).

Thank you,

```sh
 ~  pip install gpt-code-assistant                                                                                                                                                       INT ✘  10:35:59 
ERROR: Could not find a version that satisfies the requirement gpt-code-assistant (from versions: none)
ERROR: No matching distribution found for gpt-code-assistant
```

EDIT: my workaround for now is to: `poetry build && pip install aaa.whl && gpt-code-assistant ...`

**Comment by narenmanoharan** [comment]
Sorry about that! I just published the package on pypi - https://pypi.org/project/gpt-code-assistant/

Looks like I skipped that step 😓
